### PR TITLE
Adds interactive session scroller

### PR DESCRIPTION
**Pull request by alexpiet**
Adds an interactive session plot that allows the user to scroll through the session, and zoom in and out with keyboard presses

example:
Screenshot 2024-08-26 at 1 52 09 PM

### CODE REVIEW

**Comment by hanhou** [comment]
This looks great! We can also turn it to plotly and embed it in the streamlit app.

**Comment by alexpiet** [comment]
@hanhou This is ready for review (linting took forever!)

**Comment by hanhou** [comment]
Are you planning to add a test function of it eventually?

**Comment by alexpiet** [comment]
> Are you planning to add a test function of it eventually?

I wasn't going to. My thinking is that any test function would only check whether the plot is generated, and not whether the plot is accurate. It seemed like extra work without value. Open to being convinced otherwise if you think its valuable.

**Review by hanhou — APPROVED** [review]

**Comment by hanhou** [comment]
Okay fair enough.

**Pull request merged**
