### PR TITLE
feat: add plotly plots

### PR DESCRIPTION
**Pull request by hanhou**
- Plotly version of Alex's newly added plot (https://github.com/AllenNeuralDynamics/aind-dynamic-foraging-basic-analysis/pull/11 and #13 ) that can be explored in the Streamlit app as well as Jupyter Notebook.

animation

- TODO: add my previous plotly plots for trial-based session plot: https://github.com/AllenNeuralDynamics/foraging-behavior-browser/blob/main/code/util/foraging_plotly.py

### CODE REVIEW

**Comment by alexpiet** [comment]
Cool! I should learn plotly
How did you embed the video in the github post?
You should update this to also support the FIP data like my PR. Should be very easy

**Comment by hanhou** [comment]
> How did you embed the video in the github post?
I'm using [this open source tool](https://www.screentogif.com/) on Windows

> You should update this to also support the FIP data like my PR. Should be very easy
I saw that PR. Will do!

**Comment by hanhou** [comment]
@alexpiet @rachelstephlee this is ready for review.

**Review by alexpiet — APPROVED** [review]

**Comment by alexpiet** [comment]
@hanhou Can you sync with `main` and merge this in? I have more plotting updates and I want to get this merged in first

**Pull request merged**
