### PR TITLE
Annotating licks into bouts

### PR DESCRIPTION
**Pull request by alexpiet**
- segments licks into bouts based on a threshold of the interlick interval
    - currently ignores whether the licks are left/right
    - Sets the threshold as 700ms, which is simply what I used in a previous project
- updates plot_session_scroller to color licks by the lick bout
- updates plots to take nwb-like objects
- annotates which lick triggered a reward, and whether the lick bout was a rewarded or unrewarded bout
- [x] merge dependency: https://github.com/AllenNeuralDynamics/aind-dynamic-foraging-data-utils/pull/39
- [x] merge dependency: https://github.com/AllenNeuralDynamics/aind-dynamic-foraging-data-utils/pull/40
- [x] fix import dependency issue 
- [x] add unit tests for new code

### Add lick annotations to session scroller
```
from aind_dynamic_foraging_data_utils import nwb_utils as nu
from aind_dynamic_foraging_basic_analysis.plot import plot_foraging_session as pfs

nwb = nu.load_nwb_from_filename(<filepath>)
nwb.fip_df = nu.create_fib_df(nwb, tidy=True)
pfs.plot_session_scroller(nwb, plot_bouts=True)
```
Screenshot 2024-09-03 at 12 50 11 PM

### Compute FIP PSTH aligned to rewarded and unrewarded goCues
```
from aind_dynamic_foraging_data_utils import nwb_utils as nu
from aind_dynamic_foraging_basic_analysis.plot import plot_fip as pf

nwb = nu.load_nwb_from_filename(<filepath>)
nwb.df_trials = nu.create_df_trials(nwb)
rewarded_go_cues = nwb.df_trials.query('reward == 1')['goCue_start_time_absolute'].values
unrewarded_go_cues = nwb.df_trials.query('reward == 0')['goCue_start_time_absolute'].values
pf.plot_fip_psth_compare_alignments(nwb, {'rewarded goCue':rewarded_go_cues,'unrewarded goCue':unrewarded_go_cues}, 'G_1_preprocessed', censor=True)
```

Screenshot 2024-09-03 at 12 37 30 PM

### Compute FIP PSTH aligned to rewarded and unrewarded lick bout starts
```
from aind_dynamic_foraging_data_utils import nwb_utils as nu
from aind_dynamic_foraging_basic_analysis.licks import annotation as a
from aind_dynamic_foraging_basic_analysis.plot import plot_fip as pf

nwb = nu.load_nwb_from_filename(<filepath>)
nwb.df_licks = a.annotate_rewards(nwb)
rewarded_bout_start = nwb.df_licks.query('bout_start & bout_rewarded').timestamps.values
unrewarded_bout_start = nwb.df_licks.query('bout_start & (not bout_rewarded)').timestamps.values
pf.plot_fip_psth_compare_alignments(nwb, {'rewarded bout start':rewarded_bout_start,'unrewarded bout start':unrewarded_bout_start}, 'G_1_preprocessed', censor=True)
```

Screenshot 2024-09-03 at 12 37 38 PM

### CODE REVIEW

**Comment by alexpiet** [comment]
@rachelstephlee @hanhou This is ready for review

**Comment by hanhou** [comment]
> Compute FIP PSTH aligned to rewarded and unrewarded lick bout starts

Haven't checked the code, but a quick question: are bouts independent of trials? In other words, if there are more than one bouts in a trial, all bouts from the second on are considered as "unrewarded bouts" (red circles below)?

image

We may also need to align PSTH to the first bout after the go cue (essentially the "choice lick").

**Comment by alexpiet** [comment]
> > Compute FIP PSTH aligned to rewarded and unrewarded lick bout starts
> 
> Haven't checked the code, but a quick question: are bouts independent of trials? In other words, if there are more than one bouts in a trial, all bouts from the second on are considered as "unrewarded bouts" (red circles below)?
> 
> image
> 
> We may also need to align PSTH to the first bout after the go cue (essentially the "choice lick").

The concept of a `bout` here is not connected to a trial. In the example snippet you highlighted the light green bout is rewarded, and all the other bouts are unrewarded. 

We could add another annotation of bouts as "first after a go cue" (or whatever we want to call it).

**Comment by alexpiet** [comment]
@hanhou I went ahead and added a function `annotate_cue_response` that annotates licks and bouts whether they were the first lick/bout after a go cue

**Comment by alexpiet** [comment]
```
from aind_dynamic_foraging_data_utils import nwb_utils as nu
from aind_dynamic_foraging_basic_analysis.licks import annotation as a
from aind_dynamic_foraging_basic_analysis.plot import plot_fip as pf

nwb = nu.load_nwb_from_filename(<filepath>)
nwb.df_events = nu.create_events_df(nwb)
nwb.df_licks = a.annotate_rewards(nwb)
nwb.df_licks = a.annotate_cue_response(nwb)
rewarded_response_bout_start = nwb.df_licks.query('bout_start & bout_rewarded & bout_cue_response').timestamps.values
unrewarded_response_bout_start = nwb.df_licks.query('bout_start & (not bout_rewarded) & bout_cue_response').timestamps.values
pf.plot_fip_psth_compare_alignments(nwb, {'rewarded response bout start':rewarded_response_bout_start,'unrewarded response bout start':unrewarded_response_bout_start}, 'G_1_preprocessed', censor=True)
```


Screenshot 2024-09-05 at 6 22 23 PM

**Review by hanhou — APPROVED** [review]

**Pull request merged**
